version: "3.8"

services:
  mongodb:
    image: mongo:4.4.7
    restart: unless-stopped
    env_file: .env  # must be on the root of the app
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - ./data:/data/db

